build:
	gcc -Wfatal-errors \
	-std=c99 \
	./"snake_v1.c" \
	-I"C:\libsdl\include" \
	-L"C:\libsdl\lib" \
	-lmingw32 \
	-lSDL2main \
	-lSDL2 \
	-lSDL2_image \
	-lSDL2_ttf \
	-o "snake_v1.exe"